--[[
LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
--]]

local lcm = require('lcm')

local setmetatable = setmetatable
local ipairs = ipairs
local table = table
local string = string
local unpack = unpack

-- buffer helper for decoding
local _buffer_helper = {}
_buffer_helper.__index = _buffer_helper

function _buffer_helper:new(data_str)

  local obj = {buffer = data_str, index = 1}
  setmetatable(obj, self)

  return obj
end

function _buffer_helper:read(n_bytes)

  local partial = self.buffer:sub(self.index, self.index + n_bytes - 1)
  self.index = self.index + n_bytes

  if self.index > #self.buffer + 1 then
    error('buffer ran out of bytes')
  end

  return partial
end

local byte_array_t = {}
byte_array_t.__index = byte_array_t

byte_array_t.name = 'lcmtest.byte_array_t'
byte_array_t.packagename = 'lcmtest'
byte_array_t.shortname = 'byte_array_t'

function byte_array_t:new()

  local obj = {}

  obj.num_bytes = 0
  obj.data = {}

  setmetatable(obj, self)

  return obj
end

function byte_array_t._get_hash_recursive(parents)

  local newparents = {}

  for _, v in ipairs(parents) do
    if v == byte_array_t then return lcm._hash.new('0x0') end
    table.insert(newparents, v)
  end

  table.insert(newparents, byte_array_t)

  local hash = lcm._hash.new('0x870c7477e270debf')
  hash:rotate(1)

  return hash
end

byte_array_t._packed_fingerprint = lcm._pack.pack('>X', byte_array_t._get_hash_recursive({}))

function byte_array_t:encode()

  return byte_array_t._packed_fingerprint .. self:_encode_one()
end

function byte_array_t:_encode_one()

  local buf_table = {}

  table.insert(buf_table, lcm._pack.pack('>i', self.num_bytes))
  table.insert(buf_table, lcm._pack.pack(string.format('>%dB', self.num_bytes), unpack(self.data)))

  return table.concat(buf_table)
end

function byte_array_t.decode(data)

  if data:sub(1, 8) ~= byte_array_t._packed_fingerprint then
    error('bad fingerprint')
  end

  return byte_array_t._decode_one(data:sub(9))
end

function byte_array_t._decode_one(data)

  if not data.read then
    data = _buffer_helper:new(data)
  end

  local obj = byte_array_t:new()

  obj.num_bytes = lcm._pack.unpack('>i', data:read(4))
  obj.data = {lcm._pack.unpack(string.format('>%dB', obj.num_bytes), data:read(obj.num_bytes))}

  return obj
end

return byte_array_t

