--[[
LCM package init.lua file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
--]]

local M = {}

M.bools_t = require('lcmtest.bools_t')
M.byte_array_t = require('lcmtest.byte_array_t')
M.comments_t = require('lcmtest.comments_t')
M.exampleconst_t = require('lcmtest.exampleconst_t')
M.multidim_array_t = require('lcmtest.multidim_array_t')
M.node_t = require('lcmtest.node_t')
M.primitives_list_t = require('lcmtest.primitives_list_t')
M.primitives_t = require('lcmtest.primitives_t')

return M

