--[[
LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
--]]

local lcm = require('lcm')

local setmetatable = setmetatable
local ipairs = ipairs
local table = table
local string = string
local unpack = unpack

-- buffer helper for decoding
local _buffer_helper = {}
_buffer_helper.__index = _buffer_helper

function _buffer_helper:new(data_str)

  local obj = {buffer = data_str, index = 1}
  setmetatable(obj, self)

  return obj
end

function _buffer_helper:read(n_bytes)

  local partial = self.buffer:sub(self.index, self.index + n_bytes - 1)
  self.index = self.index + n_bytes

  if self.index > #self.buffer + 1 then
    error('buffer ran out of bytes')
  end

  return partial
end

local node_t = {}
node_t.__index = node_t

node_t.name = 'lcmtest.node_t'
node_t.packagename = 'lcmtest'
node_t.shortname = 'node_t'

function node_t:new()

  local obj = {}

  obj.num_children = 0
  obj.children = {}

  setmetatable(obj, self)

  return obj
end

function node_t._get_hash_recursive(parents)

  local newparents = {}

  for _, v in ipairs(parents) do
    if v == node_t then return lcm._hash.new('0x0') end
    table.insert(newparents, v)
  end

  table.insert(newparents, node_t)

  local hash = lcm._hash.new('0x98ff4a363aeb7273')
    + node_t._get_hash_recursive(newparents)
  hash:rotate(1)

  return hash
end

node_t._packed_fingerprint = lcm._pack.pack('>X', node_t._get_hash_recursive({}))

function node_t:encode()

  return node_t._packed_fingerprint .. self:_encode_one()
end

function node_t:_encode_one()

  local buf_table = {}

  table.insert(buf_table, lcm._pack.pack('>i', self.num_children))
  for i0 = 1, self.num_children do
    table.insert(buf_table, self.children[i0]:_encode_one())
  end

  return table.concat(buf_table)
end

function node_t.decode(data)

  if data:sub(1, 8) ~= node_t._packed_fingerprint then
    error('bad fingerprint')
  end

  return node_t._decode_one(data:sub(9))
end

function node_t._decode_one(data)

  if not data.read then
    data = _buffer_helper:new(data)
  end

  local obj = node_t:new()

  obj.num_children = lcm._pack.unpack('>i', data:read(4))
  obj.children = {}
  for i0 = 1, obj.num_children do
    obj.children[i0] = node_t._decode_one(data)
  end

  return obj
end

return node_t

