/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps implements lcm.lcm.LCMEncodable
{
    public float timestamp;
    public float lat;
    public float longi;
    public long utmX;
    public long utmY;
    public float alt;
    public short fixQ;
 
    public gps()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0e7769484406493bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.gps.class))
            return 0L;
 
        classes.add(exlcm.gps.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.timestamp); 
 
        outs.writeFloat(this.lat); 
 
        outs.writeFloat(this.longi); 
 
        outs.writeLong(this.utmX); 
 
        outs.writeLong(this.utmY); 
 
        outs.writeFloat(this.alt); 
 
        outs.writeShort(this.fixQ); 
 
    }
 
    public gps(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.gps _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.gps o = new exlcm.gps();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readFloat();
 
        this.lat = ins.readFloat();
 
        this.longi = ins.readFloat();
 
        this.utmX = ins.readLong();
 
        this.utmY = ins.readLong();
 
        this.alt = ins.readFloat();
 
        this.fixQ = ins.readShort();
 
    }
 
    public exlcm.gps copy()
    {
        exlcm.gps outobj = new exlcm.gps();
        outobj.timestamp = this.timestamp;
 
        outobj.lat = this.lat;
 
        outobj.longi = this.longi;
 
        outobj.utmX = this.utmX;
 
        outobj.utmY = this.utmY;
 
        outobj.alt = this.alt;
 
        outobj.fixQ = this.fixQ;
 
        return outobj;
    }
 
}

