/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gpgga_data implements lcm.lcm.LCMEncodable
{
    public float timestamp;
    public float latitude;
    public String direction1;
    public float longitude;
    public String direction2;
    public float altitude;
    public long utm_x;
    public long utm_y;
 
    public gpgga_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2673a8361099e227L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.gpgga_data.class))
            return 0L;
 
        classes.add(exlcm.gpgga_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeFloat(this.timestamp); 
 
        outs.writeFloat(this.latitude); 
 
        __strbuf = new char[this.direction1.length()]; this.direction1.getChars(0, this.direction1.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeFloat(this.longitude); 
 
        __strbuf = new char[this.direction2.length()]; this.direction2.getChars(0, this.direction2.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeFloat(this.altitude); 
 
        outs.writeLong(this.utm_x); 
 
        outs.writeLong(this.utm_y); 
 
    }
 
    public gpgga_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gpgga_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.gpgga_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.gpgga_data o = new exlcm.gpgga_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = ins.readFloat();
 
        this.latitude = ins.readFloat();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.direction1 = new String(__strbuf);
 
        this.longitude = ins.readFloat();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.direction2 = new String(__strbuf);
 
        this.altitude = ins.readFloat();
 
        this.utm_x = ins.readLong();
 
        this.utm_y = ins.readLong();
 
    }
 
    public exlcm.gpgga_data copy()
    {
        exlcm.gpgga_data outobj = new exlcm.gpgga_data();
        outobj.timestamp = this.timestamp;
 
        outobj.latitude = this.latitude;
 
        outobj.direction1 = this.direction1;
 
        outobj.longitude = this.longitude;
 
        outobj.direction2 = this.direction2;
 
        outobj.altitude = this.altitude;
 
        outobj.utm_x = this.utm_x;
 
        outobj.utm_y = this.utm_y;
 
        return outobj;
    }
 
}

