"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps(object):
    __slots__ = ["timestamp", "lat", "longi", "utmX", "utmY", "alt", "fixQ"]

    def __init__(self):
        self.timestamp = 0.0
        self.lat = 0.0
        self.longi = 0.0
        self.utmX = 0
        self.utmY = 0
        self.alt = 0.0
        self.fixQ = 0

    def encode(self):
        buf = BytesIO()
        buf.write(gps._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fffqqfh", self.timestamp, self.lat, self.longi, self.utmX, self.utmY, self.alt, self.fixQ))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps()
        self.timestamp, self.lat, self.longi, self.utmX, self.utmY, self.alt, self.fixQ = struct.unpack(">fffqqfh", buf.read(34))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps in parents: return 0
        tmphash = (0xe7769484406493b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps._packed_fingerprint is None:
            gps._packed_fingerprint = struct.pack(">Q", gps._get_hash_recursive([]))
        return gps._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

